// SegundoParcial/semana13/src/components/comercianteForm.vue
<!-- Hecho por Leo Holguín Chávez -->
 
<script setup lang="ts">
import { ref, watch, defineProps, defineEmits } from 'vue'
import type { Comerciante } from '../types/IComerciante'

const props = defineProps<{
  initialData?: Comerciante
}>()

const emit = defineEmits<{
  (e: 'submit', data: Partial<Comerciante>): void
}>()

const formData = ref<Partial<Comerciante>>({
  nombre: '',
  email: '',
  telefono: '',
  direccion: '',
  habilitado: true,
})

// Actualiza el formulario si initialData cambia
watch(
  () => props.initialData,
  (newVal) => {
    if (newVal) {
      formData.value = { ...newVal }
    } else {
      formData.value = {
        nombre: '',
        email: '',
        telefono: '',
        direccion: '',
        habilitado: true,
      }
    }
  },
  { immediate: true }
)

function handleSubmit() {
  emit('submit', { ...formData.value })
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <h2>{{ props.initialData ? 'Editar' : 'Crear' }} Comerciante</h2>
    <input name="nombre" v-model="formData.nombre" placeholder="Nombre" required />
    <input name="email" v-model="formData.email" placeholder="Email" required />
    <input name="telefono" v-model="formData.telefono" placeholder="Teléfono" required />
    <input name="direccion" v-model="formData.direccion" placeholder="Dirección" required />
    <button type="submit">Guardar</button>
  </form>
</template>

// SegundoParcial/semana14/src/app/components/comerciante-form/comerciante-form.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { Comerciante } from '../../models/comerciante.model';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
@Component({
  selector: 'app-comerciante-form',
  standalone: true,

  templateUrl: './comerciante-form.component.html',
  imports: [CommonModule, FormsModule],
  styleUrls: ['./comerciante-form.component.css']
})
export class ComercianteFormComponent implements OnChanges {
  @Input() initialData?: Comerciante;
  @Output() submit = new EventEmitter<Partial<Comerciante>>();

  formData: Partial<Comerciante> = {
    nombre: '',
    email: '',
    telefono: '',
    direccion: '',
    habilitado: true
  };

  ngOnChanges(changes: SimpleChanges) {
    if (changes['initialData']) {
      if (this.initialData) {
        this.formData = { ...this.initialData };
      } else {
        this.formData = {
          nombre: '',
          email: '',
          telefono: '',
          direccion: '',
          habilitado: true
        };
      }
    }
  }

  handleSubmit() {
    this.submit.emit({ ...this.formData });
  }
}
<form (ngSubmit)="handleSubmit()">
  <h2>{{ initialData ? 'Editar' : 'Crear' }} Comerciante</h2>
  <input name="nombre" [(ngModel)]="formData.nombre" placeholder="Nombre" required />
  <input name="email" [(ngModel)]="formData.email" placeholder="Email" required />
  <input name="telefono" [(ngModel)]="formData.telefono" placeholder="Teléfono" required />
  <input name="direccion" [(ngModel)]="formData.direccion" placeholder="Dirección" required />
  <button type="submit">Guardar</button>
</form>
