// SegundoParcial/semana13/src/components/comercianteList.vue
<!-- Hecho por Leo Holguín Chávez -->

<script setup lang="ts">
import type { Comerciante } from "../types/IComerciante";
import comercianteCard from "./comercianteCard.vue"

const props = defineProps<{
  comerciantes: Comerciante[]
}>()

const emit = defineEmits<{
  (e: 'edit', comerciante: Comerciante): void
  (e: 'delete', id: number): void
}>()

function handleEdit(comerciante: Comerciante) {
  emit('edit', comerciante)
}

function handleDelete(id: number) {
  emit('delete', id)
}
</script>

<template>
  <div>
    <comercianteCard
      v-for="comerciante in comerciantes"
      :key="comerciante.id_comerciante"
      :comerciante="comerciante"
      @edit="handleEdit"
      @delete="handleDelete"
    />
  </div>
</template>

// SegundoParcial/semana11/src/components/comercianteList.tsx
import type { Comerciante } from "../types/comerciante";
import ComercianteCard from "./ComercianteCard";

// FUE HECHO POR LEO HOLGUIN
interface Props {
  comerciantes: Comerciante[];
  onEdit: (comerciante: Comerciante) => void;
  onDelete: (id: string) => void;
}

export default function ComercianteList({ comerciantes, onEdit, onDelete }: Props) {
  return (
    <div>
      <h2>Lista de Comerciantes</h2>
      {comerciantes.map((inc) => (
        <ComercianteCard
          key={inc.id_comerciante}
          comerciante={inc}
          onEdit={onEdit}
          onDelete={onDelete}
        />
      ))}
    </div>
  );
}
