// SegundoParcial/semana13/src/components/comercianteForm.vue
<!-- Hecho por Leo Holguín Chávez -->
 
<script setup lang="ts">
import { ref, watch, defineProps, defineEmits } from 'vue'
import type { Comerciante } from '../types/IComerciante'

const props = defineProps<{
  initialData?: Comerciante
}>()

const emit = defineEmits<{
  (e: 'submit', data: Partial<Comerciante>): void
}>()

const formData = ref<Partial<Comerciante>>({
  nombre: '',
  email: '',
  telefono: '',
  direccion: '',
  habilitado: true,
})

// Actualiza el formulario si initialData cambia
watch(
  () => props.initialData,
  (newVal) => {
    if (newVal) {
      formData.value = { ...newVal }
    } else {
      formData.value = {
        nombre: '',
        email: '',
        telefono: '',
        direccion: '',
        habilitado: true,
      }
    }
  },
  { immediate: true }
)

function handleSubmit() {
  emit('submit', { ...formData.value })
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <h2>{{ props.initialData ? 'Editar' : 'Crear' }} Comerciante</h2>
    <input name="nombre" v-model="formData.nombre" placeholder="Nombre" required />
    <input name="email" v-model="formData.email" placeholder="Email" required />
    <input name="telefono" v-model="formData.telefono" placeholder="Teléfono" required />
    <input name="direccion" v-model="formData.direccion" placeholder="Dirección" required />
    <button type="submit">Guardar</button>
  </form>
</template>

// SegundoParcial/semana11/src/components/comercianteForm.tsx
import { useState, useEffect } from 'react';
import type { Comerciante } from '../types/comerciante';

// FUE HECHO POR Leo Holguin
interface Props {
  initialData?: Comerciante;
  onSubmit: (data: Partial<Comerciante>) => void;
}

export default function ComercianteForm({ initialData, onSubmit }: Props) {
  const [formData, setFormData] = useState<Partial<Comerciante>>({
    nombre: '',
    email: '',
    telefono: '',
    direccion: '',
    habilitado: true,
  });

  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
    }
  }, [initialData]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log(formData)
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit}>
      <h2>{initialData ? 'Editar' : 'Crear'} Comerciante</h2>
      <input name="nombre" value={formData.nombre || ''} onChange={handleChange} placeholder="Nombre" required />
      <input name="email" value={formData.email || ''} onChange={handleChange} placeholder="Email" required />
      <input name="telefono" value={formData.telefono || ''} onChange={handleChange} placeholder="Teléfono" required />
      <input name="direccion" value={formData.direccion || ''} onChange={handleChange} placeholder="Dirección" required />
      <button type="submit">Guardar</button>
    </form>
  );
}
