// SegundoParcial/semana13/src/components/IncidenciaForm.vue
<!-- Hecho por Neysser Delgado Meza-->
 
<script setup lang="ts">
import { ref, watch} from 'vue'
import type {Incidencia} from '../types/incidencia';

const props = defineProps<{
  incidencias?: Incidencia
}>()

const emit = defineEmits<{
  (e: 'submit', data: Partial<Incidencia>): void
}>()

const formData = ref<Partial<Incidencia>>({
  descripcion: '',
  fecha: '',
  estado: '',
  id_comerciante: 0,
})

// Actualiza el formulario si incidencias cambia
watch(
  () => props.incidencias,
  (nuevoValor) => {
    if (nuevoValor) {
      formData.value = { ...nuevoValor }
    } else {
      formData.value = {
        descripcion: '',
        fecha: '',
        estado: '',
        id_comerciante: 0,
      }
    }
  },
  { immediate: true }
)

function handleSubmit() {
  emit('submit', { ...formData.value })
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <h2>{{ props.incidencias ? 'Editar' : 'Crear' }} Incidencias</h2>
    <input name="descripcion" v-model="formData.descripcion" placeholder="Descripcion" required />
    <input name="fecha" v-model="formData.fecha" placeholder="Fecha" required />
    <input name="estado" v-model="formData.estado" placeholder="Estado" required />
    <input name="id_comerciante" v-model="formData.id_comerciante" placeholder="id_comerciante" required />
    <button type="submit">Guardar</button>
  </form>
</template>

// SegundoParcial/semana11/src/components/IncidenciaForm.tsx
import { useState, useEffect } from 'react';
import type { CreateIncidenciaInput, Incidencia } from '../types/incidencia';


// FUE HECHO POR NEYSSER DELGADO MEZA
interface Props {
  initialData?: Incidencia;
  onSubmit: (data: CreateIncidenciaInput | Incidencia) => void;
}

export default function IncidenciaForm({ initialData, onSubmit }: Props) {
  const [formData, setFormData] = useState<CreateIncidenciaInput>({
    descripcion: '',
    fecha: '',
    estado: 'pendiente',
    id_comerciante: 0,
  });

  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
    }
  }, [initialData]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit}>
      <h2>{initialData ? 'Editar' : 'Crear'} Incidencia</h2>
      <input
        name="descripcion"
        value={formData.descripcion}
        onChange={handleChange}
        placeholder="Descripción"
        required
      />
      <input
        name="fecha"
        type="date"
        value={formData.fecha}
        onChange={handleChange}
        required
      />
      <select name="estado" value={formData.estado} onChange={handleChange}>
        <option value="pendiente">Pendiente</option>
        <option value="abierto">Abierto</option>
        <option value="resuelto">Resuelto</option>
      </select>
      <input
        name="id_comerciante"
        type="number"
        value={formData.id_comerciante}
        onChange={handleChange}
        placeholder="ID Comerciante"
        required
      />
      <button type="submit">Guardar</button>
    </form>
  );
}
