// SegundoParcial/semana11/src/components/comercianteCard.tsx
import type { Comerciante } from "../types/comerciante";

// FUE HECHO POR LEO HOLGUIN
interface Props {
  comerciante: Comerciante;
  onEdit: (comerciante: Comerciante) => void;
  onDelete: (id: string) => void;
}

export default function ComercianteCard({ comerciante, onEdit, onDelete }: Props) {
  return (
    <div className="comerciante">
      <h3>Comerciante #{comerciante.id_comerciante}</h3>
      <p><strong>Nombre:</strong> {comerciante.nombre}</p>
      <p><strong>Email:</strong> {comerciante.email}</p>
      <p><strong>Teléfono:</strong> {comerciante.telefono}</p>
      <p><strong>Dirección:</strong> {comerciante.direccion}</p>
      <p><strong>Habilitado:</strong> {comerciante.habilitado}</p>

      <button onClick={() => onEdit(comerciante)}>Editar</button>
      <button onClick={() => onDelete(comerciante.id_comerciante)}>Eliminar</button>
    </div>
  );
}

// SegundoParcial/semana14/src/app/components/comerciante-card/comerciante-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Comerciante } from '../../models/comerciante.model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-comerciante-card',
  standalone: true,
  templateUrl: './comerciante-card.component.html',
  styleUrls: ['./comerciante-card.component.css'],
  imports: [CommonModule]
})
export class ComercianteCardComponent {
  @Input() comerciante!: Comerciante;
  @Output() edit = new EventEmitter<Comerciante>();
  @Output() delete = new EventEmitter<number>();

  onEdit() {
    this.edit.emit(this.comerciante);
  }

  onDelete() {
    this.delete.emit(this.comerciante.id_comerciante);
  }
}

<div class="comerciante">
  <h3>Comerciante #{{ comerciante.id_comerciante }}</h3>
  <p><strong>Nombre:</strong> {{ comerciante.nombre }}</p>
  <p><strong>Email:</strong> {{ comerciante.email }}</p>
  <p><strong>Teléfono:</strong> {{ comerciante.telefono }}</p>
  <p><strong>Dirección:</strong> {{ comerciante.direccion }}</p>
  <p><strong>Habilitado:</strong> {{ comerciante.habilitado }}</p>
  <button (click)="onEdit()">Editar</button>
  <button (click)="onDelete()">Eliminar</button>
</div>
