// SegundoParcial/semana13/src/components/IncidenciaForm.vue
<!-- Hecho por Neysser Delgado Meza-->
 
<script setup lang="ts">
import { ref, watch} from 'vue'
import type {Incidencia} from '../types/incidencia';

const props = defineProps<{
  incidencias?: Incidencia
}>()

const emit = defineEmits<{
  (e: 'submit', data: Partial<Incidencia>): void
}>()

const formData = ref<Partial<Incidencia>>({
  descripcion: '',
  fecha: '',
  estado: '',
  id_comerciante: 0,
})

// Actualiza el formulario si incidencias cambia
watch(
  () => props.incidencias,
  (nuevoValor) => {
    if (nuevoValor) {
      formData.value = { ...nuevoValor }
    } else {
      formData.value = {
        descripcion: '',
        fecha: '',
        estado: '',
        id_comerciante: 0,
      }
    }
  },
  { immediate: true }
)

function handleSubmit() {
  emit('submit', { ...formData.value })
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <h2>{{ props.incidencias ? 'Editar' : 'Crear' }} Incidencias</h2>
    <input name="descripcion" v-model="formData.descripcion" placeholder="Descripcion" required />
    <input name="fecha" v-model="formData.fecha" placeholder="Fecha" required />
    <input name="estado" v-model="formData.estado" placeholder="Estado" required />
    <input name="id_comerciante" v-model="formData.id_comerciante" placeholder="id_comerciante" required />
    <button type="submit">Guardar</button>
  </form>
</template>

// SegundoParcial/semana14/src/app/components/incidencia-form/incidencia-form.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import type { Incidencia } from '../../models/incidencia.model.ts'; // Ajusta la ruta si es necesario
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-incidencia-form',
  standalone: true,
  templateUrl: './incidencia-form.component.html',
  styleUrls: ['./incidencia-form.component.css'],
  imports: [CommonModule, FormsModule]
})
export class IncidenciaFormComponent implements OnChanges{
  @Input() incidencia?: Incidencia;
  @Output() submit = new EventEmitter<Partial<Incidencia>>();

  formData: Partial<Incidencia> = {
    descripcion: '',
    fecha: '',
    estado: '',
    id_comerciante: 0,
  };

  ngOnChanges(changes: SimpleChanges) {
    if (changes['incidencia']) {
      if (this.incidencia) {
        this.formData = { ...this.incidencia };
      } else {
        this.formData = {
          descripcion: '',
          fecha: '',
          estado: '',
          id_comerciante: 0,
        };
      }
    }
  }

  onSubmit() {
    this.submit.emit({ ...this.formData });
  }
}

<form (ngSubmit)="onSubmit()">
  <h2>{{ incidencia ? 'Editar' : 'Crear' }} Incidencias</h2>
  <input
    name="descripcion"
    [(ngModel)]="formData.descripcion"
    placeholder="Descripcion"
    required
    #descripcion="ngModel"
  />
  <input
    name="fecha"
    [(ngModel)]="formData.fecha"
    placeholder="Fecha"
    required
    #fecha="ngModel"
  />
  <input
    name="estado"
    [(ngModel)]="formData.estado"
    placeholder="Estado"
    required
    #estado="ngModel"
  />
  <input
    name="id_comerciante"
    type="number"
    [(ngModel)]="formData.id_comerciante"
    placeholder="id_comerciante"
    required
    #id_comerciante="ngModel"
  />
  <button type="submit">Guardar</button>
</form>
